[project]
name = "harlequin-postgres"
version = "0.1.0"
description = "Add a short description here"
authors = ["kobayashi <jacklink853@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
harlequin-postgres = ">=0.4.0,<0.5"
linkify-it-py = ">=2.0.3,<3"
